/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/config/backups/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Download the most recent completed configuration backup
     * @description Owner-authenticated archive including necessary credentials. Expires at the next backup or restart.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Configuration archive */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/x-tar": string;
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Authenticate the single administrator */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            password: string;
          };
        };
      };
      responses: {
        /** @description HttpOnly SameSite=Strict cookie and CSRF token */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              csrf_token: string;
              /** Format: date-time */
              expires_at: string;
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    /** Revoke current session */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Logged out */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components["responses"]["Error"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Process live */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Active configuration available */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description No active configuration */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Retained admitted-query totals; rejected admissions are separate. Missing history is 503. */
    get: {
      parameters: {
        query?: {
          /** @description Inclusive UTC RFC3339 timestamp; default is to minus one hour. */
          from?: components["parameters"]["From"];
          /** @description Exclusive UTC RFC3339 timestamp; default is current UTC minute. */
          to?: components["parameters"]["To"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Retained totals and observation completeness */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["HistorySummary"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/timeseries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description At most 1500 buckets. Auto resolution is 60, then 3600, then 86400 seconds
     *     according to the point budget. Full buckets use retained rollups; partial
     *     first/last buckets aggregate retained detail without expanding the requested
     *     window. Partial edges can therefore be incomplete after detail retention.
     *     In incomplete windows empty buckets are gaps with null counters, not zero
     *     traffic. Populated buckets retain actual counts but are marked incomplete.
     */
    get: {
      parameters: {
        query?: {
          /** @description Inclusive UTC RFC3339 timestamp; default is to minus one hour. */
          from?: components["parameters"]["From"];
          /** @description Exclusive UTC RFC3339 timestamp; default is current UTC minute. */
          to?: components["parameters"]["To"];
          resolution_seconds?: 60 | 3600 | 86400;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Bounded history buckets */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["HistorySeries"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/rankings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Top ten clients by admitted requests and exact domains by blocks; stable identity ties. */
    get: {
      parameters: {
        query?: {
          /** @description Inclusive UTC RFC3339 timestamp; default is to minus one hour. */
          from?: components["parameters"]["From"];
          /** @description Exclusive UTC RFC3339 timestamp; default is current UTC minute. */
          to?: components["parameters"]["To"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Exact retained rankings */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["HistoryRankings"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/queries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description Descending timestamp and ID keyset page with a fixed insertion ceiling.
     *     Cursor binds normalized filters and window. With a cursor, omitted from/to
     *     reuse its original window; repeat the same filters on every page. Malformed
     *     cursors and changed filters/range return 400 bad_request. Unknown or repeated
     *     parameters are rejected. No offset pagination or substring-name search.
     */
    get: {
      parameters: {
        query?: {
          /** @description Inclusive UTC RFC3339 timestamp; default is to minus one hour. */
          from?: components["parameters"]["From"];
          /** @description Exclusive UTC RFC3339 timestamp; default is current UTC minute. */
          to?: components["parameters"]["To"];
          limit?: components["parameters"]["Limit"];
          cursor?: string;
          /** @description Exact name; accepts canonical DNS decimal escapes from displayed names, or dot for root. */
          name?: string;
          /** @description Literal observed IPv4 or IPv6 address without zone */
          client?: string;
          outcome?: components["schemas"]["Outcome"];
          /** @description DNS type mnemonic, decimal 1–65535, or TYPE<number> */
          qtype?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Retained query page */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["HistoryQueries"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/queries/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    /** @description One retained event with boot-scoped historical rule metadata; 404 if absent or expired. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Available historical fields, explicitly distinguishing missing metadata */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["HistoryDetail"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Authoritative parsed configuration (no secret file contents), status, or configuration_error for invalid disk text */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              status?: components["schemas"]["Activation"];
              config?: Record<string, never>;
              configuration_error?: string;
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    trace?: never;
  };
  "/api/v1/lists": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Configured items, not discovered statistics */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              status?: components["schemas"]["Activation"];
              items?: unknown[];
              configuration_error?: string;
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    /** @description Append one item using revision and item */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    /** @description Remove item using revision and zero-based index */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    trace?: never;
  };
  "/api/v1/rules": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Configured items, not discovered statistics */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              status?: components["schemas"]["Activation"];
              items?: unknown[];
              configuration_error?: string;
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    /** @description Append one item using revision and item */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    /** @description Remove item using revision and zero-based index */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    trace?: never;
  };
  "/api/v1/records": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Configured items, not discovered statistics */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              status?: components["schemas"]["Activation"];
              items?: unknown[];
              configuration_error?: string;
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    /** @description Append one item using revision and item */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    /** @description Remove item using revision and zero-based index */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    trace?: never;
  };
  "/api/v1/clients": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Configured overrides in items, plus optional bounded retained observations and cached names. */
    get: {
      parameters: {
        query?: {
          /** @description Inclusive UTC RFC3339 timestamp; default is to minus one hour. */
          from?: components["parameters"]["From"];
          /** @description Exclusive UTC RFC3339 timestamp; default is current UTC minute. */
          to?: components["parameters"]["To"];
          limit?: components["parameters"]["Limit"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description DNS-observed address identities, not a physical-device inventory */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ClientsResponse"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    /** @description Append one item using revision and item */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    /** @description Remove item using revision and zero-based index */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    trace?: never;
  };
  "/api/v1/upstreams": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Configured items, not discovered statistics */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              status?: components["schemas"]["Activation"];
              items?: unknown[];
              configuration_error?: string;
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    /** @description Append one item using revision and item */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    /** @description Remove item using revision and zero-based index */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    trace?: never;
  };
  "/api/v1/diagnostics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Configuration and installed diagnostic measurements */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/blocking": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Object with status, enabled, pause_until (RFC3339 UTC) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components["responses"]["Error"];
      };
    };
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            revision: string;
            enabled: boolean;
            /**
             * Format: date-time
             * @description Absolute future expiry required when enabled is false
             */
            pause_until?: string;
          };
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/rules/test": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
            /** @description Name-policy matcher is QTYPE independent */
            qtype?: string;
            generation?: string;
          };
        };
      };
      responses: {
        /** @description name, normalized, generation, decision from active policy matcher; not a DNS lookup */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/config/transactions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Validate/stage settings edits without activation */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        /** @description id (opaque content hash) and revision; commit explicitly */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/config/transactions/{id}/commit": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Last 32 jobs, process lifetime only */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              items?: components["schemas"]["Job"][];
            };
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @enum {string} */
            kind: "refresh" | "backup" | "restore";
            input?: unknown;
          };
        };
      };
      responses: {
        /** @description Accepted; one running job maximum */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Job"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description SSE: reset requires summary refetch; status includes configuration and jobs, at most once/second. Eight clients, two-second write deadline. No replay history. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/event-stream": string;
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Unsigned integer encoded as a decimal string, including values beyond JavaScript exact integers. */
    Decimal: string;
    HistoryRange: {
      /** Format: date-time */
      from: string;
      /** Format: date-time */
      to: string;
    };
    /** @enum {string} */
    Outcome:
      | "local"
      | "blocked"
      | "cache"
      | "stale"
      | "forwarded"
      | "error"
      | "rejected";
    HistorySummary: {
      range: components["schemas"]["HistoryRange"];
      /** @description Admitted terminal query count */
      queries: components["schemas"]["Decimal"];
      blocked: components["schemas"]["Decimal"];
      fresh: components["schemas"]["Decimal"];
      stale: components["schemas"]["Decimal"];
      rejected: components["schemas"]["Decimal"];
      /** @description Sum of admitted query durations in microseconds */
      duration_us: components["schemas"]["Decimal"];
      complete: boolean;
      /** Format: date-time */
      updated_at: string;
    };
    HistoryQuery: {
      id: components["schemas"]["Decimal"];
      /** @description Boot scope for generation and rule identifiers */
      boot_id: string;
      sequence: components["schemas"]["Decimal"];
      /** Format: date-time */
      time: string;
      /** @description Observed address */
      client: string;
      /** @description Current cached friendly name; empty when unknown */
      client_name: string;
      client_name_source: string;
      client_name_fresh: boolean;
      /** @description Lowercase byte-safe DNS presentation with decimal escapes; root is empty */
      name: string;
      /** @description DNS type mnemonic or TYPE<number> */
      qtype: string;
      qtype_code: number;
      qclass: number;
      outcome: components["schemas"]["Outcome"];
      rcode: number;
      duration_us: components["schemas"]["Decimal"];
      generation: components["schemas"]["Decimal"];
      rule_id: components["schemas"]["Decimal"];
      upstream_id: components["schemas"]["Decimal"];
      /** @description Bits 0 TCP, 1 coalesced, 2 fallback used, 3 truncated, 4 response-policy block */
      flags: number;
    };
    HistoryQueries: {
      items: components["schemas"]["HistoryQuery"][];
      /** @description Omitted on the last page; opaque base64url value */
      next_cursor?: string;
      /** @description Observation/retention completeness */
      complete: boolean;
      range: components["schemas"]["HistoryRange"];
      /** Format: date-time */
      updated_at: string;
    };
    HistoryDetail: components["schemas"]["HistoryQuery"] & {
      /** @description One retained matched alias */
      alias?: string;
      alias_available: boolean;
      rule_description?: string;
      rule_description_available: boolean;
      /** @constant */
      alias_chain_available: false;
      /** @constant */
      upstream_attempts_available: false;
      /** @constant */
      cache_age_available: false;
      /** @constant */
      ad_trust_available: false;
      /** Format: date-time */
      updated_at: string;
    };
    HistoryRankings: {
      clients: {
        address: string;
        name: string;
        count: components["schemas"]["Decimal"];
      }[];
      domains: {
        name: string;
        count: components["schemas"]["Decimal"];
      }[];
      complete: boolean;
      range: components["schemas"]["HistoryRange"];
      /** Format: date-time */
      updated_at: string;
    };
    OutcomeCounts: {
      local: components["schemas"]["Decimal"];
      blocked: components["schemas"]["Decimal"];
      cache: components["schemas"]["Decimal"];
      stale: components["schemas"]["Decimal"];
      forwarded: components["schemas"]["Decimal"];
      error: components["schemas"]["Decimal"];
      rejected: components["schemas"]["Decimal"];
    };
    HistoryPoint: {
      /**
       * Format: date-time
       * @description Bucket start clipped to from for a partial first bucket; ends at the next point or range.to
       */
      time: string;
      outcomes: components["schemas"]["OutcomeCounts"] | null;
      duration_us: components["schemas"]["Decimal"] | null;
      /** @description Exclusive microsecond upper bounds: 100, 500, 1000, 5000, 10000, 100000, 1000000, infinity; all terminal outcomes */
      histogram: components["schemas"]["Decimal"][] | null;
      /** @description Conservative coverage status for the aligned interior or individual partial edge */
      complete: boolean;
      /** @description No observed counts in an incomplete window; null counters must not be graphed as zero */
      gap: boolean;
    };
    HistorySeries: {
      points: components["schemas"]["HistoryPoint"][];
      /** @enum {integer} */
      resolution_seconds: 60 | 3600 | 86400;
      complete: boolean;
      range: components["schemas"]["HistoryRange"];
      /** Format: date-time */
      updated_at: string;
    };
    ObservedClients: {
      items: {
        address: string;
        name: string;
        name_source: string;
        name_fresh: boolean;
        count: components["schemas"]["Decimal"];
        blocked: components["schemas"]["Decimal"];
        /** Format: date-time */
        last_seen: string;
      }[];
      complete: boolean;
      /** @description More than limit observed addresses; distinct from missing observation coverage */
      truncated: boolean;
      range: components["schemas"]["HistoryRange"];
      /** Format: date-time */
      updated_at: string;
    };
    ClientsResponse: {
      status: components["schemas"]["Activation"];
      items?: {
        address: string;
        name: string;
      }[];
      configuration_error?: string;
      observed_available: boolean;
      observed?: components["schemas"]["ObservedClients"];
    };
    Activation: {
      saved_revision: string;
      active_revision: string;
      active_generation: string;
      pending: boolean;
      recovered: boolean;
      restart_required: boolean;
      error?: string;
      sources: Record<string, never>[];
    };
    Mutation: {
      revision: string;
      edits?: {
        path: string[];
        value: string | number | boolean;
      }[];
      item?: unknown;
      index?: number;
    };
    Job: {
      id: string;
      kind: string;
      /** @enum {string} */
      state: "running" | "succeeded" | "failed";
      /** Format: date-time */
      created: string;
      result?: unknown;
      error?: string;
    };
    Error: {
      error: {
        code: string;
        message: string;
        request_id: string;
        active_generation?: string;
        field_errors: Record<string, never>[];
      };
    };
  };
  responses: {
    /** @description Validated and activated configuration */
    Activation: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Activation"];
      };
    };
    /** @description 400 malformed/bad_request, 401 auth, 403 CSRF/Host/Origin, 404 missing or expired detail, 409 revision/generation conflict, 422 validation, 429 capacity, 503 unavailable */
    Error: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: {
    /** @description Inclusive UTC RFC3339 timestamp; default is to minus one hour. */
    From: string;
    /** @description Exclusive UTC RFC3339 timestamp; default is current UTC minute. */
    To: string;
    Limit: number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
