/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/openapi.json": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read the authenticated OpenAPI document as JSON */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Authoritative OpenAPI document */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": Record<string, never>;
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/openapi.yaml": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read the authenticated OpenAPI document as YAML */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Authoritative OpenAPI document */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/yaml": string;
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tokens": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List active full-administrator bearer tokens */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Metadata only; plaintext tokens cannot be retrieved */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              items: components["schemas"]["Token"][];
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    /**
     * Create an opaque full-administrator bearer token
     * @description At most 32 active tokens. Store the returned plaintext token; it is shown only once. Token management is not an MCP tool.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
          };
        };
      };
      responses: {
        /** @description Created token and one-time plaintext credential */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Token"] & {
              /** @description Opaque full-administrator bearer credential returned only at creation */
              readonly token: string;
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tokens/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke a bearer token immediately */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Token revoked; subsequent requests with it are unauthorized */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @constant */
              revoked: true;
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Change the administrator password
     * @description Accepts 1–1024 UTF-8 bytes, including admin; no forced-change flow.
     *     Browser-session requests require the session cookie, Origin and X-CSRF-Token;
     *     bearer-authenticated requests do not require browser Origin/CSRF credentials.
     *     The permission-protected Unix socket uses filesystem authentication.
     *     Publishes an immutable credential generation through the configuration coordinator.
     *     All previous browser sessions are revoked before success returns; log in again.
     *     Bearer tokens have a separate lifetime and are revoked explicitly through token management.
     *     Pending external configuration edits or concurrent writes can return 409.
     *     CLI equivalent is dimsum control password @- with the same JSON body.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["PasswordChange"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/catalog": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Inspect predefined subscription choices
     * @description Availability describes parser support, not download state. Defaults are metadata and do not enable subscriptions. CLI equivalent is dimsum control catalog.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Predefined catalog metadata */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Catalog"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/config/backups/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Download the most recent completed configuration backup
     * @description Owner-authenticated archive including necessary credentials. Expires at the next backup or restart.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Configuration archive */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/x-tar": string;
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Authenticate the single administrator */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            password: string;
          };
        };
      };
      responses: {
        /** @description HttpOnly SameSite=Strict cookie and CSRF token */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              csrf_token: string;
              /** Format: date-time */
              expires_at: string;
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    /** Revoke current session */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Logged out */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components["responses"]["Error"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Process live */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Active configuration available */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description No active configuration */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Retained admitted-query totals; rejected admissions are separate. Missing history is 503. */
    get: {
      parameters: {
        query?: {
          /** @description Inclusive UTC RFC3339 timestamp; default is to minus one hour. */
          from?: components["parameters"]["From"];
          /** @description Exclusive UTC RFC3339 timestamp; default is current UTC minute. */
          to?: components["parameters"]["To"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Retained totals and observation completeness */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["HistorySummary"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/timeseries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description At most 1500 buckets. Auto resolution is 60, then 3600, then 86400 seconds
     *     according to the point budget. Full buckets use retained rollups; partial
     *     first/last buckets aggregate retained detail without expanding the requested
     *     window. Partial edges can therefore be incomplete after detail retention.
     *     In incomplete windows empty buckets are gaps with null counters, not zero
     *     traffic. Populated buckets retain actual counts but are marked incomplete.
     */
    get: {
      parameters: {
        query?: {
          /** @description Inclusive UTC RFC3339 timestamp; default is to minus one hour. */
          from?: components["parameters"]["From"];
          /** @description Exclusive UTC RFC3339 timestamp; default is current UTC minute. */
          to?: components["parameters"]["To"];
          resolution_seconds?: 60 | 3600 | 86400;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Bounded history buckets */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["HistorySeries"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/rankings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Top ten clients by admitted requests and exact domains by blocks; stable identity ties. */
    get: {
      parameters: {
        query?: {
          /** @description Inclusive UTC RFC3339 timestamp; default is to minus one hour. */
          from?: components["parameters"]["From"];
          /** @description Exclusive UTC RFC3339 timestamp; default is current UTC minute. */
          to?: components["parameters"]["To"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Exact retained rankings */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["HistoryRankings"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/queries": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description Descending timestamp and ID keyset page with a fixed insertion ceiling.
     *     Cursor binds normalized filters and window. With a cursor, omitted from/to
     *     reuse its original window; repeat the same filters on every page. Malformed
     *     cursors and changed filters/range return 400 bad_request. Unknown or repeated
     *     parameters are rejected. No offset pagination or substring-name search.
     */
    get: {
      parameters: {
        query?: {
          /** @description Inclusive UTC RFC3339 timestamp; default is to minus one hour. */
          from?: components["parameters"]["From"];
          /** @description Exclusive UTC RFC3339 timestamp; default is current UTC minute. */
          to?: components["parameters"]["To"];
          limit?: components["parameters"]["Limit"];
          cursor?: string;
          /** @description Exact name; accepts canonical DNS decimal escapes from displayed names, or dot for root. */
          name?: string;
          /** @description Literal observed IPv4 or IPv6 address without zone */
          client?: string;
          outcome?: components["schemas"]["Outcome"];
          /** @description DNS type mnemonic, decimal 1–65535, or TYPE<number> */
          qtype?: string;
          /** @description Exact process boot identity; required with rule_id or upstream_id */
          boot_id?: string;
          /** @description Canonical uint32 decimal configuration generation; required with rule_id or upstream_id */
          generation?: string;
          /** @description Canonical uint32 decimal rule number, scoped by boot_id and generation */
          rule_id?: string;
          /** @description Canonical uint16 decimal upstream number, scoped by boot_id and generation because endpoints can change on reload */
          upstream_id?: string;
          /** @description Exact archived source identity, at most 512 UTF-8 bytes. Legacy or oversized identities are unavailable, never inferred from descriptions. */
          source_id?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Retained query page */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["HistoryQueries"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/queries/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    /** @description One retained event with boot-scoped historical rule metadata; 404 if absent or expired. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Available historical fields, explicitly distinguishing missing metadata */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["HistoryDetail"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Authoritative parsed configuration (no secret file contents), status, or configuration_error for invalid disk text */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              status?: components["schemas"]["Activation"];
              config?: Record<string, never>;
              configuration_error?: string;
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    trace?: never;
  };
  "/api/v1/lists": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Configured items, not discovered statistics */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              status?: components["schemas"]["Activation"];
              items?: unknown[];
              configuration_error?: string;
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    /** @description Append one item using revision and item */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    /** @description Remove item using revision and zero-based index */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    trace?: never;
  };
  "/api/v1/rules": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Configured items, not discovered statistics */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              status?: components["schemas"]["Activation"];
              items?: unknown[];
              configuration_error?: string;
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    /** @description Append one item using revision and item */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    /** @description Remove item using revision and zero-based index */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    trace?: never;
  };
  "/api/v1/records": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Configured items, not discovered statistics */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              status?: components["schemas"]["Activation"];
              items?: unknown[];
              configuration_error?: string;
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    /** @description Append one item using revision and item */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    /** @description Remove item using revision and zero-based index */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    trace?: never;
  };
  "/api/v1/clients": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Configured overrides in items, plus optional bounded retained observations and cached names. */
    get: {
      parameters: {
        query?: {
          /** @description Inclusive UTC RFC3339 timestamp; default is to minus one hour. */
          from?: components["parameters"]["From"];
          /** @description Exclusive UTC RFC3339 timestamp; default is current UTC minute. */
          to?: components["parameters"]["To"];
          limit?: components["parameters"]["Limit"];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description DNS-observed address identities, not a physical-device inventory */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ClientsResponse"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    /** @description Append one item using revision and item */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    /** @description Remove item using revision and zero-based index */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    trace?: never;
  };
  "/api/v1/upstreams": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Configured items, not discovered statistics */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              status?: components["schemas"]["Activation"];
              items?: unknown[];
              configuration_error?: string;
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    /** @description Append one item using revision and item */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    /** @description Remove item using revision and zero-based index */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    trace?: never;
  };
  "/api/v1/diagnostics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Configuration and installed diagnostic measurements. dns_addresses lists client-facing IP:port endpoints from running DNS listeners, expanding wildcard binds to interface addresses and excluding loopback and link-local addresses. IPv6 endpoints use brackets. An empty list means no client-facing address was discovered. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/blocking": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Object with status, enabled, pause_until (RFC3339 UTC) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components["responses"]["Error"];
      };
    };
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            revision: string;
            enabled: boolean;
            /**
             * Format: date-time
             * @description Absolute future expiry required when enabled is false
             */
            pause_until?: string;
          };
        };
      };
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/rules/test": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
            /** @description Name-policy matcher is QTYPE independent */
            qtype?: string;
            generation?: string;
          };
        };
      };
      responses: {
        /** @description name, normalized, generation, decision from active policy matcher; not a DNS lookup */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/config/transactions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Validate/stage settings edits without activation */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Mutation"];
        };
      };
      responses: {
        /** @description id (opaque content hash) and revision; commit explicitly */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/config/transactions/{id}/commit": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components["responses"]["Activation"];
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Last 32 jobs, process lifetime only */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              items?: components["schemas"]["Job"][];
            };
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** @enum {string} */
            kind:
              | "refresh"
              | "backup"
              | "restore"
              | "upstream-probe"
              | "support-bundle";
            /** @description For upstream-probe use UpstreamProbeInput; for support-bundle use SupportBundleInput. Diagnostic input is capped at 4 KiB. Validation failures are reported in the asynchronous job status. */
            input?: unknown;
          } & (unknown & unknown);
        };
      };
      responses: {
        /** @description Accepted; one running job maximum */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Job"];
          };
        };
        default: components["responses"]["Error"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description SSE: reset requires summary refetch; status includes configuration and jobs, at most once/second. Eight clients, two-second write deadline. No replay history. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/event-stream": string;
          };
        };
        default: components["responses"]["Error"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Token: {
      /** @description Opaque token metadata identifier; never a credential */
      id: string;
      name: string;
      /** Format: date-time */
      created_at: string;
    };
    PasswordChange: {
      /** @description Nonempty password, maximum 1024 UTF-8 bytes. Fresh installations initialize a salted hash of admin only when no credential exists. */
      password: string;
    };
    Catalog: {
      items: components["schemas"]["CatalogItem"][];
    };
    CatalogItem: {
      id: string;
      label: string;
      description: string;
      /** Format: uri */
      url: string;
      /** @enum {string} */
      dialect: "hosts" | "domains" | "dns-adblock";
      /** @enum {string} */
      domain_kind: "exact" | "suffix";
      available: boolean;
      unavailable_reason: string;
      default_enabled: boolean;
    };
    UpstreamProbeInput: {
      /** @description Literal IP:port currently configured in the active primary or fallback pool; arbitrary destinations are rejected */
      endpoint: string;
      /** @default 1000 */
      timeout_ms: number;
    };
    /**
     * @description One isolated root NS check using the validated DNS exchange engine. UDP
     *     may retry over TCP on truncation, at most two attempts within one deadline.
     *     Live configuration, cache, and upstream circuit state are unchanged. All
     *     actual attempts count once as non-client health probes; no client traffic
     *     or history event is recorded. Response errors/timeouts are completed
     *     diagnostic findings; parent cancellation fails the job.
     */
    UpstreamProbeResult: {
      endpoint: string;
      generation: components["schemas"]["Decimal"];
      /** @constant */
      name: ".";
      /** @constant */
      qtype: "NS";
      /** @enum {string} */
      state: "healthy" | "responding_error" | "no_valid_response" | "cancelled";
      /** @description A validated DNS response was observed */
      responding: boolean;
      /** @description This isolated check returned NOERROR; not a live circuit-state claim */
      healthy: boolean;
      rcode?: number;
      /**
       * @description Omitted when validated response transport is unavailable
       * @enum {string}
       */
      transport?: "udp" | "tcp";
      attempts: components["schemas"]["Decimal"];
      diagnostic_probes: components["schemas"]["Decimal"];
      duration_us: components["schemas"]["Decimal"];
      timeout_ms: number;
      error?: string;
      /** Format: date-time */
      checked_at: string;
    };
    /** @description History is omitted by default. Explicit opt-in also requires an explicit positive UTC from/to range of at most 24 hours. Range and limit are rejected without opt-in. */
    SupportBundleInput: {
      /** @default false */
      include_query_history: boolean;
      /** Format: date-time */
      from?: string;
      /** Format: date-time */
      to?: string;
      /** @default 50 */
      limit: number;
    };
    /** @description JSON job result capped at 256 KiB; oversized bundles fail explicitly. No secret file contents or archive. URL userinfo, query values, and fragments are redacted, including diagnostic error messages. */
    SupportBundleResult: {
      /** @constant */
      format: "dimsum-support-v1";
      /** Format: date-time */
      generated_at: string;
      build: {
        go_version: string;
        os: string;
        architecture: string;
        /** @description Embedded Go module version or unknown; development builds can report '(devel)' */
        version: string;
        revision?: string;
        modified?: string;
      };
      /** @description Redacted settings inspection including saved/active status */
      configuration: Record<string, never>;
      diagnostics: Record<string, never>;
      /** @constant */
      contains_secrets: false;
      contains_query_history: boolean;
      query_history: components["schemas"]["HistoryQueries"] | null;
    };
    /** @description Unsigned integer encoded as a decimal string, including values beyond JavaScript exact integers. */
    Decimal: string;
    HistoryRange: {
      /** Format: date-time */
      from: string;
      /** Format: date-time */
      to: string;
    };
    /** @enum {string} */
    Outcome:
      | "local"
      | "blocked"
      | "cache"
      | "stale"
      | "forwarded"
      | "error"
      | "rejected";
    HistorySummary: {
      range: components["schemas"]["HistoryRange"];
      /** @description Admitted terminal query count */
      queries: components["schemas"]["Decimal"];
      blocked: components["schemas"]["Decimal"];
      fresh: components["schemas"]["Decimal"];
      stale: components["schemas"]["Decimal"];
      rejected: components["schemas"]["Decimal"];
      /** @description Sum of admitted query durations in microseconds */
      duration_us: components["schemas"]["Decimal"];
      complete: boolean;
      /** Format: date-time */
      updated_at: string;
    };
    HistoryQuery: {
      id: components["schemas"]["Decimal"];
      /** @description Boot scope for generation and rule identifiers */
      boot_id: string;
      sequence: components["schemas"]["Decimal"];
      /** Format: date-time */
      time: string;
      /** @description Observed address */
      client: string;
      /** @description Current cached friendly name; empty when unknown */
      client_name: string;
      client_name_source: string;
      client_name_fresh: boolean;
      client_device?: components["schemas"]["DeviceEnrichment"];
      /** @description Lowercase byte-safe DNS presentation with decimal escapes; root is empty */
      name: string;
      /** @description DNS type mnemonic or TYPE<number> */
      qtype: string;
      qtype_code: number;
      qclass: number;
      outcome: components["schemas"]["Outcome"];
      rcode: number;
      duration_us: components["schemas"]["Decimal"];
      generation: components["schemas"]["Decimal"];
      rule_id: components["schemas"]["Decimal"];
      /** @description Exact archived source identity; empty when unavailable (including legacy history and identities exceeding 512 bytes) */
      source_id?: string;
      upstream_id: components["schemas"]["Decimal"];
      /** @description Bits 0 TCP, 1 coalesced, 2 fallback used, 3 truncated, 4 response-policy block */
      flags: number;
    };
    HistoryQueries: {
      items: components["schemas"]["HistoryQuery"][];
      /** @description Omitted on the last page; opaque base64url value */
      next_cursor?: string;
      /** @description Observation/retention completeness */
      complete: boolean;
      range: components["schemas"]["HistoryRange"];
      /** Format: date-time */
      updated_at: string;
    };
    HistoryDetail: components["schemas"]["HistoryQuery"] & {
      /** @description One retained matched alias */
      alias?: string;
      alias_available: boolean;
      rule_description?: string;
      rule_description_available: boolean;
      /** @constant */
      alias_chain_available: false;
      /** @constant */
      upstream_attempts_available: false;
      /** @constant */
      cache_age_available: false;
      /** @constant */
      ad_trust_available: false;
      /** Format: date-time */
      updated_at: string;
    };
    HistoryRankings: {
      clients: {
        device?: components["schemas"]["DeviceEnrichment"];
        address: string;
        name: string;
        count: components["schemas"]["Decimal"];
      }[];
      domains: {
        name: string;
        count: components["schemas"]["Decimal"];
      }[];
      complete: boolean;
      range: components["schemas"]["HistoryRange"];
      /** Format: date-time */
      updated_at: string;
    };
    OutcomeCounts: {
      local: components["schemas"]["Decimal"];
      blocked: components["schemas"]["Decimal"];
      cache: components["schemas"]["Decimal"];
      stale: components["schemas"]["Decimal"];
      forwarded: components["schemas"]["Decimal"];
      error: components["schemas"]["Decimal"];
      rejected: components["schemas"]["Decimal"];
    };
    HistoryPoint: {
      /**
       * Format: date-time
       * @description Bucket start clipped to from for a partial first bucket; ends at the next point or range.to
       */
      time: string;
      outcomes: components["schemas"]["OutcomeCounts"] | null;
      duration_us: components["schemas"]["Decimal"] | null;
      /** @description Exclusive microsecond upper bounds: 100, 500, 1000, 5000, 10000, 100000, 1000000, infinity; all terminal outcomes */
      histogram: components["schemas"]["Decimal"][] | null;
      /** @description Conservative coverage status for the aligned interior or individual partial edge */
      complete: boolean;
      /** @description No observed counts in an incomplete window; null counters must not be graphed as zero */
      gap: boolean;
    };
    HistorySeries: {
      points: components["schemas"]["HistoryPoint"][];
      /** @enum {integer} */
      resolution_seconds: 60 | 3600 | 86400;
      complete: boolean;
      range: components["schemas"]["HistoryRange"];
      /** Format: date-time */
      updated_at: string;
    };
    ObservedClients: {
      items: {
        device?: components["schemas"]["DeviceEnrichment"];
        address: string;
        name: string;
        name_source: string;
        name_fresh: boolean;
        count: components["schemas"]["Decimal"];
        blocked: components["schemas"]["Decimal"];
        /** Format: date-time */
        last_seen: string;
      }[];
      complete: boolean;
      /** @description More than limit observed addresses; distinct from missing observation coverage */
      truncated: boolean;
      range: components["schemas"]["HistoryRange"];
      /** Format: date-time */
      updated_at: string;
    };
    DeviceEvidence: {
      source: string;
      hostname?: string;
      service_type?: string;
      label?: string;
      model?: string;
      manufacturer?: string;
      device_type?: string;
      /** Format: date-time */
      updated: string;
      /** Format: date-time */
      expires: string;
    };
    /** @description Current derived device presentation; explicit client names always take priority over discovered names. Not an authenticated physical identity. */
    DeviceEnrichment: {
      /** @enum {string} */
      category:
        | "unknown"
        | "phone"
        | "tablet"
        | "laptop"
        | "desktop"
        | "tv"
        | "speaker"
        | "printer"
        | "camera"
        | "lighting"
        | "appliance"
        | "server";
      reason: string;
      inferred: boolean;
      fresh: boolean;
      hostname?: string;
      model?: string;
      manufacturer?: string;
      evidence: components["schemas"]["DeviceEvidence"][];
    };
    ClientsResponse: {
      status: components["schemas"]["Activation"];
      items?: {
        address: string;
        name: string;
      }[];
      configuration_error?: string;
      observed_available: boolean;
      observed?: components["schemas"]["ObservedClients"];
    };
    Activation: {
      saved_revision: string;
      active_revision: string;
      active_generation: string;
      pending: boolean;
      recovered: boolean;
      restart_required: boolean;
      error?: string;
      sources: Record<string, never>[];
      /** @description Unaccepted exact local A/AAAA names pointing to this admin listener; returned after saving records. Approval is a separate revision-checked records PATCH. */
      dashboard_hosts?: {
        name: string;
        host: string;
        /** Format: uri */
        url: string;
      }[];
    };
    Mutation: {
      revision: string;
      /** @description For PATCH /records only, without edits/item/index: accept this saved local A/AAAA name for dashboard access. Rechecks local interface and admin listener, persists admin.allowed_hosts, and activates without restart. */
      accept_admin_host?: string;
      edits?: {
        path: string[];
        /** @description String arrays are accepted only for naming.mdns.interfaces; other paths require scalars. */
        value: (string | number | boolean) | string[];
      }[];
      item?: unknown;
      index?: number;
    };
    Job: {
      id: string;
      kind: string;
      /** @enum {string} */
      state: "running" | "succeeded" | "failed";
      /** Format: date-time */
      created: string;
      /** @description Kind-specific result. upstream-probe returns UpstreamProbeResult; support-bundle returns SupportBundleResult. Other job kinds retain their documented result shapes. */
      result?: unknown;
      error?: string;
    };
    Error: {
      error: {
        code: string;
        message: string;
        request_id: string;
        active_generation?: string;
        field_errors: Record<string, never>[];
      };
    };
  };
  responses: {
    /** @description Validated and activated configuration */
    Activation: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Activation"];
      };
    };
    /** @description 400 malformed/bad_request, 401 auth, 403 CSRF/Host/Origin, 404 missing or expired detail, 409 revision/generation conflict, 422 validation, 429 capacity, 503 unavailable */
    Error: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: {
    /** @description Inclusive UTC RFC3339 timestamp; default is to minus one hour. */
    From: string;
    /** @description Exclusive UTC RFC3339 timestamp; default is current UTC minute. */
    To: string;
    Limit: number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
