// Keep backend validation in sync with the installed frontend icon catalogue.
import { readFile, writeFile } from "node:fs/promises";
import dynamicIconImports from "lucide-react/dynamicIconImports.mjs";

const destination = new URL("../../internal/clients/builtin/lucide-icons.txt", import.meta.url);
const content =
  "# Generated by web/scripts/icon-names.mjs; do not edit.\n" +
  Object.keys(dynamicIconImports).sort().join("\n") +
  "\n";
if (process.argv.includes("--check")) {
  if ((await readFile(destination, "utf8")) !== content) {
    throw new Error("Lucide catalogue is stale; run npm --prefix web run icons:generate");
  }
} else {
  await writeFile(destination, content);
}
