FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /run/dimsum && chown 65532:65532 /run/dimsum && chmod 0750 /run/dimsum
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/dimsum /usr/bin/dimsum
COPY dist/metadata /usr/share/doc/dimsum/metadata
USER 65532:65532
WORKDIR /var/lib/dimsum
STOPSIGNAL SIGTERM
ENTRYPOINT ["/usr/bin/dimsum"]
CMD ["serve", "-config", "/etc/dimsum/dimsum.yaml", "-state", "/var/lib/dimsum/recovery"]
